### ISSUE TITLE
Milestones for 0.0.1

### ISSUE THREAD

**Issue by kevinyamauchi** [napari-threedee/napari-threedee#24]
Hey @alisterburt , here are the things I think we should have together for a 0.0.1 release

- [x] update readme (good explanations, nice gifs)
- [x] GUIs for manipulators and annotators
- [x] headlight for mesh
- [x] some sort of documentation on usage

**Comment by kevinyamauchi** [comment]
🎉
