### ISSUE TITLE
0.0.2 release checklist

### ISSUE THREAD

**Issue by alisterburt** [napari-threedee/napari-threedee#67]
- [x] hook up existing manipulators to new manipulator backend #65 
- [ ] spend time on docs (possibly moving to mkdocs-material published on readthedocs too)
    - [x] how to: annotate filaments
    - [ ] How to: integrate napari-threedee widget into your plugin (@kevinyamauchi can write this on the `napari-animation` widget`)
    - [x] Update any necessary parts of the manipulator docs
- [x] conda-forge build #66
   - Done. https://github.com/conda-forge/napari-threedee-feedstock

**Comment by kevinyamauchi** [comment]
Thanks, @alisterburt ! This all looks good to me. I can do the `conda-forge` recipe - I wanted to write a short how-to for that anyway. I'll tag you in the PR when I'm done.

**Comment by alisterburt** [comment]
amazing, thanks!

**Comment by psobolewskiPhD** [comment]
I think this can be closed as that release was a loooong time ago 😉 
cc: @alisterburt
